blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/SWHL/RapidVideOCR/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding RapidVideOCR.
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/SWHL/RapidVideOCR/discussions/categories/ideas
    about: Please vote for and post new feature ideas in the community forum.
  - name: ğŸ“– Documentation
    url: https://swhl.github.io/RapidVideOCR/docs
    about: A great place to find instructions and answers about RapidVideOCR.
